//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG.Lib.ServiceReferenceWSBase {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", ConfigurationName="ServiceReferenceWSBase.WSBaseSoap")]
    public interface WSBaseSoap {
        
        // CODEGEN: Generating message contract since element name TestCountResult from namespace http://www2.arnes.si/~ljc3m2/igor/iglib/index.html is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html/TestCount", ReplyAction="*")]
        IG.Lib.ServiceReferenceWSBase.TestCountResponse TestCount(IG.Lib.ServiceReferenceWSBase.TestCountRequest request);
        
        // CODEGEN: Generating message contract since element name TestServiceResult from namespace http://www2.arnes.si/~ljc3m2/igor/iglib/index.html is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html/TestService", ReplyAction="*")]
        IG.Lib.ServiceReferenceWSBase.TestServiceResponse TestService(IG.Lib.ServiceReferenceWSBase.TestServiceRequest request);
        
        // CODEGEN: Generating message contract since element name commandlineArguments from namespace http://www2.arnes.si/~ljc3m2/igor/iglib/index.html is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html/TestServiceArg", ReplyAction="*")]
        IG.Lib.ServiceReferenceWSBase.TestServiceArgResponse TestServiceArg(IG.Lib.ServiceReferenceWSBase.TestServiceArgRequest request);
        
        // CODEGEN: Generating message contract since element name commandlineArguments from namespace http://www2.arnes.si/~ljc3m2/igor/iglib/index.html is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html/TestServiceArgs", ReplyAction="*")]
        IG.Lib.ServiceReferenceWSBase.TestServiceArgsResponse TestServiceArgs(IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestCount", Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", Order=0)]
        public IG.Lib.ServiceReferenceWSBase.TestCountRequestBody Body;
        
        public TestCountRequest() {
        }
        
        public TestCountRequest(IG.Lib.ServiceReferenceWSBase.TestCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestCountRequestBody {
        
        public TestCountRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestCountResponse", Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", Order=0)]
        public IG.Lib.ServiceReferenceWSBase.TestCountResponseBody Body;
        
        public TestCountResponse() {
        }
        
        public TestCountResponse(IG.Lib.ServiceReferenceWSBase.TestCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html")]
    public partial class TestCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestCountResult;
        
        public TestCountResponseBody() {
        }
        
        public TestCountResponseBody(string TestCountResult) {
            this.TestCountResult = TestCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestService", Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", Order=0)]
        public IG.Lib.ServiceReferenceWSBase.TestServiceRequestBody Body;
        
        public TestServiceRequest() {
        }
        
        public TestServiceRequest(IG.Lib.ServiceReferenceWSBase.TestServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestServiceRequestBody {
        
        public TestServiceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestServiceResponse", Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", Order=0)]
        public IG.Lib.ServiceReferenceWSBase.TestServiceResponseBody Body;
        
        public TestServiceResponse() {
        }
        
        public TestServiceResponse(IG.Lib.ServiceReferenceWSBase.TestServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html")]
    public partial class TestServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestServiceResult;
        
        public TestServiceResponseBody() {
        }
        
        public TestServiceResponseBody(string TestServiceResult) {
            this.TestServiceResult = TestServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceArgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestServiceArg", Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", Order=0)]
        public IG.Lib.ServiceReferenceWSBase.TestServiceArgRequestBody Body;
        
        public TestServiceArgRequest() {
        }
        
        public TestServiceArgRequest(IG.Lib.ServiceReferenceWSBase.TestServiceArgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html")]
    public partial class TestServiceArgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string commandlineArguments;
        
        public TestServiceArgRequestBody() {
        }
        
        public TestServiceArgRequestBody(string commandlineArguments) {
            this.commandlineArguments = commandlineArguments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceArgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestServiceArgResponse", Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", Order=0)]
        public IG.Lib.ServiceReferenceWSBase.TestServiceArgResponseBody Body;
        
        public TestServiceArgResponse() {
        }
        
        public TestServiceArgResponse(IG.Lib.ServiceReferenceWSBase.TestServiceArgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html")]
    public partial class TestServiceArgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestServiceArgResult;
        
        public TestServiceArgResponseBody() {
        }
        
        public TestServiceArgResponseBody(string TestServiceArgResult) {
            this.TestServiceArgResult = TestServiceArgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceArgsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestServiceArgs", Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", Order=0)]
        public IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequestBody Body;
        
        public TestServiceArgsRequest() {
        }
        
        public TestServiceArgsRequest(IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html")]
    public partial class TestServiceArgsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IG.Lib.ServiceReferenceWSBase.ArrayOfString commandlineArguments;
        
        public TestServiceArgsRequestBody() {
        }
        
        public TestServiceArgsRequestBody(IG.Lib.ServiceReferenceWSBase.ArrayOfString commandlineArguments) {
            this.commandlineArguments = commandlineArguments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestServiceArgsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestServiceArgsResponse", Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html", Order=0)]
        public IG.Lib.ServiceReferenceWSBase.TestServiceArgsResponseBody Body;
        
        public TestServiceArgsResponse() {
        }
        
        public TestServiceArgsResponse(IG.Lib.ServiceReferenceWSBase.TestServiceArgsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www2.arnes.si/~ljc3m2/igor/iglib/index.html")]
    public partial class TestServiceArgsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestServiceArgsResult;
        
        public TestServiceArgsResponseBody() {
        }
        
        public TestServiceArgsResponseBody(string TestServiceArgsResult) {
            this.TestServiceArgsResult = TestServiceArgsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSBaseSoapChannel : IG.Lib.ServiceReferenceWSBase.WSBaseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSBaseSoapClient : System.ServiceModel.ClientBase<IG.Lib.ServiceReferenceWSBase.WSBaseSoap>, IG.Lib.ServiceReferenceWSBase.WSBaseSoap {
        
        public WSBaseSoapClient() {
        }
        
        public WSBaseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSBaseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBaseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSBaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IG.Lib.ServiceReferenceWSBase.TestCountResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap.TestCount(IG.Lib.ServiceReferenceWSBase.TestCountRequest request) {
            return base.Channel.TestCount(request);
        }
        
        public string TestCount() {
            IG.Lib.ServiceReferenceWSBase.TestCountRequest inValue = new IG.Lib.ServiceReferenceWSBase.TestCountRequest();
            inValue.Body = new IG.Lib.ServiceReferenceWSBase.TestCountRequestBody();
            IG.Lib.ServiceReferenceWSBase.TestCountResponse retVal = ((IG.Lib.ServiceReferenceWSBase.WSBaseSoap)(this)).TestCount(inValue);
            return retVal.Body.TestCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IG.Lib.ServiceReferenceWSBase.TestServiceResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap.TestService(IG.Lib.ServiceReferenceWSBase.TestServiceRequest request) {
            return base.Channel.TestService(request);
        }
        
        public string TestService() {
            IG.Lib.ServiceReferenceWSBase.TestServiceRequest inValue = new IG.Lib.ServiceReferenceWSBase.TestServiceRequest();
            inValue.Body = new IG.Lib.ServiceReferenceWSBase.TestServiceRequestBody();
            IG.Lib.ServiceReferenceWSBase.TestServiceResponse retVal = ((IG.Lib.ServiceReferenceWSBase.WSBaseSoap)(this)).TestService(inValue);
            return retVal.Body.TestServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IG.Lib.ServiceReferenceWSBase.TestServiceArgResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap.TestServiceArg(IG.Lib.ServiceReferenceWSBase.TestServiceArgRequest request) {
            return base.Channel.TestServiceArg(request);
        }
        
        public string TestServiceArg(string commandlineArguments) {
            IG.Lib.ServiceReferenceWSBase.TestServiceArgRequest inValue = new IG.Lib.ServiceReferenceWSBase.TestServiceArgRequest();
            inValue.Body = new IG.Lib.ServiceReferenceWSBase.TestServiceArgRequestBody();
            inValue.Body.commandlineArguments = commandlineArguments;
            IG.Lib.ServiceReferenceWSBase.TestServiceArgResponse retVal = ((IG.Lib.ServiceReferenceWSBase.WSBaseSoap)(this)).TestServiceArg(inValue);
            return retVal.Body.TestServiceArgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IG.Lib.ServiceReferenceWSBase.TestServiceArgsResponse IG.Lib.ServiceReferenceWSBase.WSBaseSoap.TestServiceArgs(IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequest request) {
            return base.Channel.TestServiceArgs(request);
        }
        
        public string TestServiceArgs(IG.Lib.ServiceReferenceWSBase.ArrayOfString commandlineArguments) {
            IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequest inValue = new IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequest();
            inValue.Body = new IG.Lib.ServiceReferenceWSBase.TestServiceArgsRequestBody();
            inValue.Body.commandlineArguments = commandlineArguments;
            IG.Lib.ServiceReferenceWSBase.TestServiceArgsResponse retVal = ((IG.Lib.ServiceReferenceWSBase.WSBaseSoap)(this)).TestServiceArgs(inValue);
            return retVal.Body.TestServiceArgsResult;
        }
    }
}
